In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("vehicles.csv")

In [7]:
df.head(5)

              DateTime  Vehicles
0  2015-11-01 00:00:00        15
1  2015-11-01 01:00:00        13
2  2015-11-01 02:00:00        10
3  2015-11-01 03:00:00         7
4  2015-11-01 04:00:00         9

In [8]:
df.shape

(48120, 2)

In [9]:
df["DateTime"]=pd.to_datetime(df["DateTime"])

df["Year"]=df["DateTime"].dt.year
df["Month"]=df["DateTime"].dt.month
df["Day"]=df["DateTime"].dt.day
df["Hour"]=df["DateTime"].dt.hour
df["Day of Week"]=df["DateTime"].dt.weekday
df["Week of Year"]=df["DateTime"].dt.isocalendar().week
df["Day of Year"]=df["DateTime"].dt.dayofyear

In [10]:
df.drop(columns=["DateTime"],axis=1,inplace=True)

In [11]:
df.head()

   Vehicles  Year  Month  Day  Hour  Day of Week  Week of Year  Day of Year
0        15  2015     11    1     0            6            44          305
1        13  2015     11    1     1            6            44          305
2        10  2015     11    1     2            6            44          305
3         7  2015     11    1     3            6            44          305
4         9  2015     11    1     4            6            44          305

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X=df.drop("Vehicles",axis=1)
y=df.Vehicles

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=22)

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
RFG=RandomForestRegressor()

In [17]:
RFG.fit(X,y)

RandomForestRegressor()

In [18]:
y_pred=RFG.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("MSE:", mse)
print("MAE:", mae)
print("R2 Score:", r2)